name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.x'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies Go
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        
    - name: Get dependencies Fyne
      run: |
        sudo apt-get install golang gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
        sudo apt-get install gcc-mingw-w64 clang
        GO111MODULE=off go get golang.org/x/tools/cmd/goimports                               
        GO111MODULE=off go get github.com/fzipp/gocyclo/cmd/gocyclo
        GO111MODULE=off go get golang.org/x/lint/golint
        GO111MODULE=off go get honnef.co/go/tools/cmd/staticcheck
        
    - name: Install fyne cmd tools
      run: |
        GO111MODULE=off go get fyne.io/fyne/cmd/fyne
        
    - name: Generate resource files
      run: ./resources.sh

    - name: Generate packages
      run: ./releaseLocal.sh

    - name: Test
      run: go test -v .

    - name: Create a Release
      uses: actions/create-release@v1.1.4
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: github.GITHUB_REF
        # The name of the release. For example, `Release v1.0.1`
        release_name: Subtitlewatcher github.GITHUB_REF
